name: Go build

on:
  push:
    branches:
      - main
      - release-*
    paths-ignore:
      - 'config/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - '**.md'
      - LICENSE
      - '**.svg'
  pull_request:
    branches:
      - main
      - release-*
    paths-ignore:
      - 'config/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - '**.md'
      - LICENSE
      - '**.svg'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for `git describe`
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: |
          make build

      - name: Build image
        run: |
          make docker-build

#  generate-sbom:
#    name: "Build :: SBOM"
#    needs: [ build ]
#
#    runs-on: ubuntu-22.04
#
#    steps:
#      - name: Check out code into the Go module directory
#        uses: actions/checkout@v4
#
#      - name: Generate SBOM
#        run: |
#          mkdir -p sbom && chmod 777 sbom
#          make sbom/spdx.json
#
#      - uses: actions/upload-artifact@v4
#        with:
#          name: spdx.json
#          path: sbom/spdx.json

  unittest:
    name: Unit test
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run unit tests
        run: |
          make test

  smoketest:
    name: Smoke test
    needs: build
    runs-on: ubuntu-22.04-8core
    strategy:
      fail-fast: false
      matrix:
        smoke-suite:
          - check-basic
          - check-hostpath
          - check-ha-controller
          - check-ha-controller-secret
          - check-jointoken
          - check-monitoring

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Create image bundle
        run: |
          make release
          make k0smotron-image-bundle.tar

      - name: Run inttest
        run: |
          make -C inttest ${{ matrix.smoke-suite }}
